"use client";

import { useEffect } from "react";

const CLOSE_ACTIONS = new Set(["ASSUME", "ACCEPT", "TRANSFER"]);

function actionFor(button: HTMLButtonElement) {
  return (button.dataset.pf24OwnerActionLabel || button.textContent || "").trim().toUpperCase();
}

function closeMenu(menu: HTMLElement) {
  // ProjectFlightTrafficV6 already closes this menu on mouse-leave. Trigger the
  // same React path first so we do not manipulate its DOM behind React's back.
  menu.dispatchEvent(new MouseEvent("mouseout", {
    bubbles: true,
    cancelable: false,
    relatedTarget: document.body,
  }));

  // Fallback for browsers/React event delegation where a synthetic mouseout does
  // not produce onMouseLeave. A background radar click uses the traffic layer's
  // normal deselect path and guarantees the menu is gone.
  window.requestAnimationFrame(() => {
    if (!menu.isConnected) return;
    const activeMenu = document.querySelector<HTMLElement>("[data-pf24-callsign-menu='true']");
    if (activeMenu !== menu) return;
    const radar = document.querySelector<HTMLElement>("main.fixed > section");
    radar?.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true }));
  });
}

export default function ScopeTrafficActionMenuCloser() {
  useEffect(() => {
    const onMouseUp = (event: MouseEvent) => {
      const target = event.target instanceof Element ? event.target : null;
      const button = target?.closest<HTMLButtonElement>("button");
      const menu = button?.closest<HTMLElement>("[data-pf24-callsign-menu='true']");
      if (!button || !menu) return;
      if (!CLOSE_ACTIONS.has(actionFor(button))) return;

      // Wait until the native click generated by this mouse-up has been handled by
      // Assume / Accept / Transfer. Then close the small callsign menu as feedback.
      window.setTimeout(() => closeMenu(menu), 0);
    };

    window.addEventListener("mouseup", onMouseUp, true);
    return () => window.removeEventListener("mouseup", onMouseUp, true);
  }, []);

  return null;
}
