"use client";
import {createPortal} from "react-dom";
import {useCallback,useEffect,useMemo,useState} from "react";
import {supabase} from "@/lib/supabase";
import {normalizeGameCallsign} from "@/lib/flightPlanGameCallsign";
import type {ScopeFlightPlan} from "@/lib/scope/types";
type Props={initialPlans:ScopeFlightPlan[]};type StoredConnection={callsign?:string};type AssumedMap=Record<string,string>;
const CONNECTION_STORAGE_KEY="pf24_scope_connection_session_v1",UNPLANNED_STORAGE_KEY="pf24_scope_unplanned_assumed_v1",GREEN="#00e000";
const norm=(v:string)=>normalizeGameCallsign(v);
function readPosition(){try{return (JSON.parse(sessionStorage.getItem(CONNECTION_STORAGE_KEY)??"null") as StoredConnection|null)?.callsign?.trim().toUpperCase()??""}catch{return""}}
function readAssumed():AssumedMap{try{const p=JSON.parse(sessionStorage.getItem(UNPLANNED_STORAGE_KEY)??"{}");return p&&typeof p==="object"&&!Array.isArray(p)?p:{}}catch{return{}}}
function save(v:AssumedMap){sessionStorage.setItem(UNPLANNED_STORAGE_KEY,JSON.stringify(v))}
function trafficCallsign(label:HTMLElement){return Array.from(label.querySelectorAll<HTMLButtonElement>("button")).find(b=>!b.closest("[data-pf24-callsign-menu='true']")&&/^[A-Z0-9-]{2,12}$/.test(b.textContent?.trim().toUpperCase()??""))?.textContent?.trim().toUpperCase()??""}
function paint(callsign:string,active:boolean){const root=document.querySelector<HTMLElement>("[data-pf24-live-traffic='true']");if(!root)return;const labels=Array.from(root.querySelectorAll<HTMLElement>("[data-pf24-traffic-label='true']"));const targets=Array.from(root.querySelectorAll<HTMLButtonElement>("[data-pf24-traffic-select='true']"));const groups=Array.from(root.querySelectorAll<SVGGElement>("svg > g"));labels.forEach((label,i)=>{if(norm(trafficCallsign(label))!==norm(callsign))return;if(active){label.style.setProperty("color",GREEN,"important");label.querySelectorAll<HTMLElement>("span,button,input").forEach(el=>{if(!el.closest("[data-pf24-callsign-menu='true']"))el.style.setProperty("color",GREEN,"important")});targets[i]?.querySelector<HTMLElement>(":scope > span")?.style.setProperty("border-color",GREEN,"important");groups[i]?.querySelectorAll<SVGLineElement>("line").forEach(el=>el.style.setProperty("stroke",GREEN,"important"));groups[i]?.querySelectorAll<SVGCircleElement>("circle").forEach(el=>el.style.setProperty("fill",GREEN,"important"))}else{label.style.removeProperty("color");label.querySelectorAll<HTMLElement>("span,button,input").forEach(el=>el.style.removeProperty("color"));targets[i]?.querySelector<HTMLElement>(":scope > span")?.style.removeProperty("border-color");groups[i]?.querySelectorAll<SVGLineElement>("line").forEach(el=>el.style.removeProperty("stroke"));groups[i]?.querySelectorAll<SVGCircleElement>("circle").forEach(el=>el.style.removeProperty("fill"))}})}
export default function ScopeUnplannedTrafficOperations({initialPlans}:Props){const[plans,setPlans]=useState(initialPlans),[position,setPosition]=useState(""),[assumed,setAssumed]=useState<AssumedMap>({}),[blankFpl,setBlankFpl]=useState(false),[host,setHost]=useState<HTMLElement|null>(null);const planned=useMemo(()=>new Set(plans.map(p=>norm(p.callsign))),[plans]);const loadPlans=useCallback(async()=>{const{data}=await supabase.from("flight_plans").select("*").neq("status","FINISHED");setPlans((data??[])as ScopeFlightPlan[])},[]);
useEffect(()=>{setPosition(readPosition());setAssumed(readAssumed());setHost(document.querySelector<HTMLElement>("main.fixed > section"));const onConn=(e:Event)=>{const d=(e as CustomEvent<{connected?:boolean;callsign?:string}>).detail;setPosition(d?.connected?(d.callsign?.trim().toUpperCase()||readPosition()):"")};window.addEventListener("pf24-scope-connection-change",onConn);return()=>window.removeEventListener("pf24-scope-connection-change",onConn)},[]);
useEffect(()=>{const ch=supabase.channel("scope-unplanned-plans").on("postgres_changes",{event:"*",schema:"public",table:"flight_plans"},()=>void loadPlans()).subscribe();return()=>{void supabase.removeChannel(ch)}},[loadPlans]);
const mine=useCallback((cs:string)=>!!position&&assumed[norm(cs)]===position,[assumed,position]);const sync=useCallback(()=>{document.querySelectorAll<HTMLElement>("[data-pf24-traffic-label='true']").forEach(label=>{const cs=trafficCallsign(label);if(cs&&!planned.has(norm(cs)))paint(cs,mine(cs))});document.querySelectorAll<HTMLElement>("[data-pf24-callsign-menu='true']").forEach(menu=>{const label=menu.closest<HTMLElement>("[data-pf24-traffic-label='true']");if(!label)return;const cs=trafficCallsign(label);if(!cs||planned.has(norm(cs)))return;const b=Array.from(menu.querySelectorAll<HTMLButtonElement>("button")).find(x=>["ASSUME","TRANSFER"].includes(x.textContent?.trim().toUpperCase()??""));if(b)b.textContent=mine(cs)?"Transfer":"Assume"})},[mine,planned]);useEffect(()=>{sync();const t=window.setInterval(sync,180);return()=>window.clearInterval(t)},[sync]);
useEffect(()=>{const onClick=(e:MouseEvent)=>{if(e.button!==0)return;const b=e.target instanceof Element?e.target.closest<HTMLButtonElement>("button"):null,menu=b?.closest<HTMLElement>("[data-pf24-callsign-menu='true']"),label=menu?.closest<HTMLElement>("[data-pf24-traffic-label='true']");if(!b||!menu||!label)return;const action=b.textContent?.trim().toUpperCase()??"";if(!["ASSUME","TRANSFER","FPL","FREE"].includes(action))return;const cs=trafficCallsign(label),key=norm(cs);if(!cs||planned.has(key))return;e.preventDefault();e.stopImmediatePropagation();if(action==="FPL"){setHost(document.querySelector<HTMLElement>("main.fixed > section"));setBlankFpl(true);return}if(action==="TRANSFER")return;if(action==="ASSUME"){if(!position){alert("Debes estar conectado a un sector activo antes de asumir tráfico.");return}setAssumed(cur=>{const next={...cur,[key]:position};save(next);return next});return}if(action==="FREE"){if(!position||assumed[key]!==position){alert("Solo puedes liberar tráfico asumido por tu mismo sector.");return}setAssumed(cur=>{const next={...cur};delete next[key];save(next);return next});paint(cs,false)}};document.addEventListener("click",onClick,true);return()=>document.removeEventListener("click",onClick,true)},[assumed,planned,position]);
const portal=host&&blankFpl?createPortal(<div className="absolute left-1/2 top-1/2 z-[120] w-[900px] max-w-[calc(100%-40px)] -translate-x-1/2 -translate-y-1/2 border border-[#888] bg-[#cecece] p-[10px] font-mono text-[#111] shadow-xl"><div className="mb-2 text-[18px]">Flight Plan</div><div className="border border-white p-[10px]"><div className="grid grid-cols-2 gap-x-[50px] gap-y-[8px]">{["Callsign","Flight Level","Departure","Cruising Speed","Arrival","Aircraft","Alternative","Fuel En Durance","Flight Rules","Acft Registration"].map(x=><BlankRow key={x} label={x}/>)}</div><div className="mt-3 grid grid-cols-2 gap-5"><BlankArea label="Route"/><BlankArea label="Remarks"/></div></div><div className="mt-3 flex justify-end"><button onClick={()=>setBlankFpl(false)} className="border border-[#888] bg-[#e8e8e8] px-4 py-1">Close</button></div></div>,host):null;return<>{portal}</>}
function BlankRow({label}:{label:string}){return<div className="grid grid-cols-[170px_1fr] items-center"><span className="pr-2 text-right text-[18px]">{label}</span><div className="h-[28px] bg-[#ececec]"/></div>}
function BlankArea({label}:{label:string}){return<div><div className="mb-1 text-[18px]">{label}</div><div className="h-[150px] bg-[#ececec]"/></div>}
