"use client";
import { createPortal } from "react-dom";
import { useCallback, useEffect, useRef, useState } from "react";
import { supabase } from "@/lib/supabase";
import { ATC_FREQUENCIES } from "@/lib/atcFrequencies";

type Chat={position:string;frequency:string};
type Msg={id:string;from:string;to:string;text:string;sentAt:number};
type State={chats:Chat[];active:string|null;history:Record<string,Msg[]>;unread:Record<string,number>};
const CONN="pf24_scope_connection_session_v1",STORE="pf24_scope_sector_chat_v2",ROOM="scope-sector-private-chat-v2",FREQ=/^\d{3}\.\d{3}$/;
const empty=():State=>({chats:[],active:null,history:{},unread:{}});
const norm=(v?:string|null)=>v?.trim().toUpperCase()??"";
function pos(){try{return norm((JSON.parse(sessionStorage.getItem(CONN)||"null") as {callsign?:string}|null)?.callsign)}catch{return ""}}
function load(p:string):State{if(!p)return empty();try{const a=JSON.parse(localStorage.getItem(STORE)||"{}") as Record<string,State>,s=a[p];if(!s)return empty();const chats=(s.chats||[]).filter(c=>c&&c.position&&FREQ.test(c.frequency)).slice(-12);return{chats,active:chats.some(c=>c.position===norm(s.active))?norm(s.active):null,history:s.history||{},unread:s.unread||{}}}catch{return empty()}}
function save(p:string,s:State){if(!p)return;try{const a=JSON.parse(localStorage.getItem(STORE)||"{}") as Record<string,State>;a[p]=s;localStorage.setItem(STORE,JSON.stringify(a))}catch{}}
function footer(){return document.querySelector<HTMLElement>("main.fixed footer")}
function freqWin(){return Array.from(document.querySelectorAll<HTMLElement>("main.fixed > section > div.absolute.z-30")).find(w=>w.firstElementChild?.textContent?.toUpperCase().includes("FREQ"))||null}
function rowInfo(row:HTMLElement){const text=row.textContent||"",f=text.match(/\b\d{3}\.\d{3}\b/)?.[0]||"",spans=Array.from(row.querySelectorAll<HTMLSpanElement>(":scope > span")).map(s=>norm(s.textContent)),p=spans.find(v=>ATC_FREQUENCIES[v]||/_(APP|TWR|GND|DEL|CTR)$/.test(v))||"";return{position:p,frequency:f}}
function setInput(input:HTMLInputElement,v:string){const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;s?.call(input,v);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}))}
function id(){return typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():`c-${Date.now()}-${Math.random()}`}
function time(t:number){const d=new Date(t);return`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}`}
export default function ScopeSectorChat(){
 const[host,setHost]=useState<HTMLElement|null>(null),[state,setState]=useState<State>(empty());
 const ref=useRef<State>(empty()),me=useRef(""),channel=useRef<ReturnType<typeof supabase.channel>|null>(null),subscribed=useRef(false),log=useRef<HTMLDivElement|null>(null);
 const replace=useCallback((s:State)=>{ref.current=s;setState(s);save(me.current,s)},[]);
 const update=useCallback((fn:(s:State)=>State)=>replace(fn(ref.current)),[replace]);
 const open=useCallback((p:string,f:string)=>{p=norm(p);f=f.trim();if(!me.current||!p||p===me.current||!FREQ.test(f))return;update(s=>{const chats=s.chats.some(c=>c.position===p)?s.chats.map(c=>c.position===p?{...c,frequency:f}:c):[...s.chats,{position:p,frequency:f}].slice(-12);return{...s,chats,active:p,unread:{...s.unread,[p]:0}}})},[update]);
 const remove=useCallback((p:string)=>update(s=>{const chats=s.chats.filter(c=>c.position!==p),history={...s.history},unread={...s.unread};delete history[p];delete unread[p];return{...s,chats,history,unread,active:s.active===p?(chats[0]?.position||null):s.active};}),[update]);
 const send=useCallback((text:string)=>{const to=ref.current.active,from=me.current;text=text.trim().slice(0,500);if(!from||!to||!text)return false;const m={id:id(),from,to,text,sentAt:Date.now()};update(s=>({...s,history:{...s.history,[to]:[...(s.history[to]||[]),m].slice(-200)}}));if(channel.current&&subscribed.current)void channel.current.send({type:"broadcast",event:"message",payload:{...m,kind:"sector-chat"}});return true},[update]);
 useEffect(()=>{me.current=pos();const s=load(me.current);ref.current=s;setState(s);setHost(footer());const on=(e:Event)=>{const d=(e as CustomEvent<{connected?:boolean;callsign?:string}>).detail;save(me.current,ref.current);me.current=d?.connected?norm(d.callsign)||pos():"";const n=load(me.current);ref.current=n;setState(n);setHost(footer())};const t=setInterval(()=>setHost(footer()),300);addEventListener("pf24-scope-connection-change",on);return()=>{save(me.current,ref.current);clearInterval(t);removeEventListener("pf24-scope-connection-change",on)}},[]);
 useEffect(()=>{const c=supabase.channel(ROOM,{config:{broadcast:{self:false}}});channel.current=c;c.on("broadcast",{event:"message"},({payload})=>{const m=payload as Partial<Msg>&{kind?:string},from=norm(m.from),to=norm(m.to);if(!me.current||m.kind!=="sector-chat"||to!==me.current||!from||from===me.current||!m.id||!m.text)return;const messageId=m.id,text=String(m.text),sentAt=Number(m.sentAt)||Date.now();update(s=>{const h=s.history[from]||[];if(h.some(x=>x.id===messageId))return s;const f=ATC_FREQUENCIES[from]||s.chats.find(x=>x.position===from)?.frequency||"---.---",chats=s.chats.some(x=>x.position===from)?s.chats.map(x=>x.position===from?{...x,frequency:f}:x):[...s.chats,{position:from,frequency:f}].slice(-12),read=s.active===from&&document.visibilityState==="visible";return{...s,chats,history:{...s.history,[from]:[...h,{id:messageId,from,to,text:text.slice(0,500),sentAt}].slice(-200)},unread:{...s.unread,[from]:read?0:(s.unread[from]||0)+1}}})}).subscribe(st=>subscribed.current=st==="SUBSCRIBED");return()=>{subscribed.current=false;channel.current=null;void supabase.removeChannel(c)}},[update]);
 useEffect(()=>{const dbl=(e:MouseEvent)=>{if(e.button!==0)return;const t=e.target instanceof Element?e.target:null;if(!t)return;const w=t.closest<HTMLElement>("main.fixed > section > div.absolute.z-30");if(!w||!w.firstElementChild?.textContent?.toUpperCase().includes("FREQ"))return;const r=t.closest<HTMLElement>("div.flex.whitespace-nowrap");if(!r)return;const{position,frequency}=rowInfo(r);if(!position||!frequency||position===me.current)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open(position,frequency);footer()?.querySelector<HTMLInputElement>("input")?.focus()};document.addEventListener("dblclick",dbl,true);return()=>document.removeEventListener("dblclick",dbl,true)},[open]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!ref.current.active||!log.current)return;const t=e.target as HTMLElement|null;if(e.key==="ArrowUp"||e.key==="ArrowDown"){if(t?.closest("select,textarea,button")&&!t?.closest("footer input"))return;e.preventDefault();log.current.scrollTop+=e.key==="ArrowUp"?-28:28;return}if(e.key!=="Enter"||!t?.closest("footer input")||e.shiftKey||e.ctrlKey||e.altKey||e.metaKey)return;const input=t as HTMLInputElement;if(!input.value.trim())return;e.preventDefault();e.stopImmediatePropagation();if(send(input.value))setInput(input,"")};document.addEventListener("keydown",key,true);return()=>document.removeEventListener("keydown",key,true)},[send]);
 useEffect(()=>{const sync=()=>{const w=freqWin();if(!w)return;w.querySelectorAll<HTMLElement>("div.flex.whitespace-nowrap").forEach(r=>{const{position}=rowInfo(r);if(!position)return;const unread=(ref.current.unread[position]||0)>0;const spans=r.querySelectorAll<HTMLSpanElement>(":scope > span");if(spans[1])spans[1].style.setProperty("color",unread?"#00efff":"",unread?"important":"")})};sync();const t=setInterval(sync,350);return()=>clearInterval(t)},[state.unread]);
 useEffect(()=>{if(ref.current.active)requestAnimationFrame(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight})},[state.active,state.history]);
 useEffect(()=>{const i=host?.querySelector<HTMLInputElement>("input");if(!i)return;const old=i.style.marginLeft;i.style.marginLeft=state.chats.length?"210px":old||"";return()=>{i.style.marginLeft=old}},[host,state.chats.length]);
 if(!host)return null;const messages=state.active?(state.history[state.active]||[]):[];
 return createPortal(<>{state.active&&<div className="pointer-events-none absolute inset-x-0 top-0 z-[45] h-[76px] bg-[#555c61] font-mono text-[9px] text-[#e8e8e8]"><div ref={log} className="pointer-events-auto h-full overflow-y-auto px-[5px] py-[5px] leading-[12px] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{messages.map(m=><div key={m.id}><span className="text-[#bfc8c6]">{time(m.sentAt)} </span><span className={m.from===me.current?"text-[#e8e8e8]":"text-[#00efff]"}>{m.from}</span><span>: {m.text}</span></div>)}</div></div>}{state.chats.length>0&&<div className="absolute bottom-[9px] left-[4px] z-[65] flex h-[18px] w-[198px] items-center gap-[3px] overflow-x-auto whitespace-nowrap font-mono text-[9px] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{state.chats.map(c=>{const u=(state.unread[c.position]||0)>0,s=state.active===c.position;return <span key={c.position} title={`${c.position} · doble click para eliminar`} onClick={()=>update(v=>({...v,active:c.position,unread:{...v.unread,[c.position]:0}}))} onDoubleClick={e=>{e.preventDefault();e.stopPropagation();remove(c.position)}} className={`cursor-default select-none px-[2px] leading-[18px] ${u?"text-[#00efff]":s?"text-[#111] underline":"text-[#333]"}`}>{c.frequency}</span>})}</div>}</>,host)
}
